In [2]:
import numpy as np

In [12]:
l = ["sagar",2,3,5,6,34,5,4,56,44,56,6,56,56,56,56]

In [13]:
type(l)

list

In [14]:
numpy.array(l)

array(['sagar', '2', '3', '5', '6', '34', '5', '4', '56', '44', '56', '6',
       '56', '56', '56', '56'], dtype='<U21')

In [15]:
type(numpy.array(l))

numpy.ndarray

In [16]:
np.array(l)

array(['sagar', '2', '3', '5', '6', '34', '5', '4', '56', '44', '56', '6',
       '56', '56', '56', '56'], dtype='<U21')

In [18]:
type(np.array(l))

numpy.ndarray

In [35]:
n = np.array([3,45,45,65,65.67,76.0])

In [21]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

In [23]:
a = np.array([["sagar","prakash"],[23,45]])

In [24]:
a

array([['sagar', 'prakash'],
       ['23', '45']], dtype='<U21')

In [26]:
b = np.array([[1,2,4,5],[35,4,3,34]])

In [27]:
b

array([[ 1,  2,  4,  5],
       [35,  4,  3, 34]])

In [28]:
a[1]

array(['23', '45'], dtype='<U21')

In [29]:
a[1][0]

'23'

In [30]:
a[1][1]

'45'

In [31]:
b

array([[ 1,  2,  4,  5],
       [35,  4,  3, 34]])

In [34]:
b[0][2]

4

In [42]:
a2 = np.array([1,2,3,4,4,5],ndmin = 4)

In [46]:
a2[0][0][0][0]

1

In [47]:
a

array([['sagar', 'prakash'],
       ['23', '45']], dtype='<U21')

In [52]:
np.asarray([1,2,4,55,6,45,656,5,65,656,63,3])

array([  1,   2,   4,  55,   6,  45, 656,   5,  65, 656,  63,   3])

In [53]:
np.asanyarray([1,2,4,55,6,45,656,5,65,656,63,3])

array([  1,   2,   4,  55,   6,  45, 656,   5,  65, 656,  63,   3])

In [54]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [57]:
a = [1,2,4,5,6,7,8]

In [58]:
np.asarray(a)

array([1, 2, 4, 5, 6, 7, 8])

In [59]:
np.mat(a)

matrix([[1, 2, 4, 5, 6, 7, 8]])

In [60]:
np.asanyarray(a)

array([1, 2, 4, 5, 6, 7, 8])

In [61]:
np.asarray(a)

array([1, 2, 4, 5, 6, 7, 8])

In [62]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 4, 5, 6, 7, 8]])

In [66]:
np.fromfunction(lambda i,j : i == j ,(9,9))

array([[ True, False, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False,  True]])

In [67]:
np.fromfunction(lambda i , j : i*j , (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [69]:
np.fromfunction(lambda i , j : i**j , (4,4),dtype=int)

array([[ 1,  0,  0,  0],
       [ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27]])

In [70]:
np.mat(np.fromfunction(lambda i , j : i**j , (4,4),dtype=int))

matrix([[ 1,  0,  0,  0],
        [ 1,  1,  1,  1],
        [ 1,  2,  4,  8],
        [ 1,  3,  9, 27]])

In [73]:
np.fromfunction(lambda i , j ,z : i*j*z , (4,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2],
        [0, 3]],

       [[0, 0],
        [0, 2],
        [0, 4],
        [0, 6]],

       [[0, 0],
        [0, 3],
        [0, 6],
        [0, 9]]])