In [1]:
import numpy as np

In [2]:
l = [1,2,4,5,5,4,34,3]

In [3]:
np.asarray(l)

array([ 1,  2,  4,  5,  5,  4, 34,  3])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
a = np.zeros((3,4,5))

In [8]:
np.copy(a)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [12]:
np.empty((4,5))

array([[2.07635989e-316, 0.00000000e+000, 7.01413727e-009,
        6.97387871e+228, 7.47011456e-114],
       [5.95750259e+271, 5.95915351e+271, 5.43256360e-096,
        1.06259729e+223, 1.14489505e-095],
       [7.16006779e-062, 9.13544126e+242, 1.05135744e-153,
        2.00007403e+174, 7.36191050e+223],
       [1.33468277e-317, 6.90794427e-310, 1.63041663e-322,
        2.13561022e-316, 6.90794427e-310]])

In [13]:
np.empty((5,4,2))

array([[[1.64155969e-316, 0.00000000e+000],
        [6.90794100e-310, 6.90794159e-310],
        [6.90794160e-310, 6.90794159e-310],
        [6.90794168e-310, 6.90794288e-310]],

       [[6.90794288e-310, 6.90794159e-310],
        [6.90794168e-310, 6.90794288e-310],
        [4.91747885e-317, 5.38007844e-317],
        [5.38005078e-317, 6.90794168e-310]],

       [[4.90219048e-317, 6.90794158e-310],
        [6.90794159e-310, 6.90794335e-310],
        [6.90794158e-310, 6.90794288e-310],
        [4.94484614e-317, 4.94400820e-317]],

       [[4.93529683e-317, 6.90794160e-310],
        [6.90794160e-310, 6.90794159e-310],
        [6.90794160e-310, 6.90794160e-310],
        [6.90794160e-310, 6.90794160e-310]],

       [[6.90794160e-310, 6.90794160e-310],
        [6.90794160e-310, 6.90794160e-310],
        [6.90794159e-310, 6.90794168e-310],
        [6.90794166e-310, 5.38380172e-317]]])

In [14]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [15]:
np.linspace(2,6,1000)

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [16]:
np.linspace(2,4,100)

array([2.        , 2.02020202, 2.04040404, 2.06060606, 2.08080808,
       2.1010101 , 2.12121212, 2.14141414, 2.16161616, 2.18181818,
       2.2020202 , 2.22222222, 2.24242424, 2.26262626, 2.28282828,
       2.3030303 , 2.32323232, 2.34343434, 2.36363636, 2.38383838,
       2.4040404 , 2.42424242, 2.44444444, 2.46464646, 2.48484848,
       2.50505051, 2.52525253, 2.54545455, 2.56565657, 2.58585859,
       2.60606061, 2.62626263, 2.64646465, 2.66666667, 2.68686869,
       2.70707071, 2.72727273, 2.74747475, 2.76767677, 2.78787879,
       2.80808081, 2.82828283, 2.84848485, 2.86868687, 2.88888889,
       2.90909091, 2.92929293, 2.94949495, 2.96969697, 2.98989899,
       3.01010101, 3.03030303, 3.05050505, 3.07070707, 3.09090909,
       3.11111111, 3.13131313, 3.15151515, 3.17171717, 3.19191919,
       3.21212121, 3.23232323, 3.25252525, 3.27272727, 3.29292929,
       3.31313131, 3.33333333, 3.35353535, 3.37373737, 3.39393939,
       3.41414141, 3.43434343, 3.45454545, 3.47474747, 3.49494

In [17]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [18]:
np.concatenate(a)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.linspace(2,6,100)

array([2.        , 2.04040404, 2.08080808, 2.12121212, 2.16161616,
       2.2020202 , 2.24242424, 2.28282828, 2.32323232, 2.36363636,
       2.4040404 , 2.44444444, 2.48484848, 2.52525253, 2.56565657,
       2.60606061, 2.64646465, 2.68686869, 2.72727273, 2.76767677,
       2.80808081, 2.84848485, 2.88888889, 2.92929293, 2.96969697,
       3.01010101, 3.05050505, 3.09090909, 3.13131313, 3.17171717,
       3.21212121, 3.25252525, 3.29292929, 3.33333333, 3.37373737,
       3.41414141, 3.45454545, 3.49494949, 3.53535354, 3.57575758,
       3.61616162, 3.65656566, 3.6969697 , 3.73737374, 3.77777778,
       3.81818182, 3.85858586, 3.8989899 , 3.93939394, 3.97979798,
       4.02020202, 4.06060606, 4.1010101 , 4.14141414, 4.18181818,
       4.22222222, 4.26262626, 4.3030303 , 4.34343434, 4.38383838,
       4.42424242, 4.46464646, 4.50505051, 4.54545455, 4.58585859,
       4.62626263, 4.66666667, 4.70707071, 4.74747475, 4.78787879,
       4.82828283, 4.86868687, 4.90909091, 4.94949495, 4.98989

In [20]:
np.linspace(2,6,10,endpoint=False).reshape(5,2)

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [21]:
np.hamming

<function numpy.hamming(M)>

In [22]:
np.linspace(2,6,10,endpoint=False,retstep=True)

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [23]:
np.logspace(2,4,10,base=2).reshape(5,2)

array([[ 4.        ,  4.66611616],
       [ 5.44316   ,  6.34960421],
       [ 7.4069977 ,  8.64047791],
       [10.0793684 , 11.75787594],
       [13.71590373, 16.        ]])

In [24]:
a = np.arange(4,40).reshape(3,6,2)

In [25]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [26]:
a.max()

39

In [27]:
a.min()

4

In [28]:
a.sum()

774

In [29]:
a = np.arange(4,40).reshape(6,6)

In [30]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [31]:
a.max(axis=1)

array([ 9, 15, 21, 27, 33, 39])

In [32]:
a.max(axis=0)

array([34, 35, 36, 37, 38, 39])

In [33]:
a = np.arange(4,40).reshape(6,6)


In [34]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [35]:
10+a

array([[14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [36]:
11+a

array([[15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50]])

In [37]:
a/0

/tmp/ipykernel_9239/4102073204.py:1: RuntimeWarning: divide by zero encountered in divide
  a/0


array([[inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf]])

In [38]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [39]:
a**2

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [40]:
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [41]:
pow(a,3)

array([[   64,   125,   216,   343,   512,   729],
       [ 1000,  1331,  1728,  2197,  2744,  3375],
       [ 4096,  4913,  5832,  6859,  8000,  9261],
       [10648, 12167, 13824, 15625, 17576, 19683],
       [21952, 24389, 27000, 29791, 32768, 35937],
       [39304, 42875, 46656, 50653, 54872, 59319]])

In [42]:
a 

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [43]:
b = np.array([2,3,1,2,3,2])

In [44]:
b = b.reshape(1,-1)
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [45]:
b.T

array([[2],
       [3],
       [1],
       [2],
       [3],
       [2]])

In [46]:
a + b

array([[ 6,  8,  7,  9, 11, 11],
       [12, 14, 13, 15, 17, 17],
       [18, 20, 19, 21, 23, 23],
       [24, 26, 25, 27, 29, 29],
       [30, 32, 31, 33, 35, 35],
       [36, 38, 37, 39, 41, 41]])

In [47]:
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [48]:
b

array([[2, 3, 1, 2, 3, 2]])

In [133]:
a + 10

array([[34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69]])

In [134]:
a = 10 + a

In [135]:
a

array([[34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63],
       [64, 65, 66, 67, 68, 69]])

In [122]:
a + b

array([[26, 28, 27, 29, 31, 31],
       [32, 34, 33, 35, 37, 37],
       [38, 40, 39, 41, 43, 43],
       [44, 46, 45, 47, 49, 49],
       [50, 52, 51, 53, 55, 55],
       [56, 58, 57, 59, 61, 61]])

In [139]:
b.T

array([[2, 3, 1, 2, 3, 2]])

In [136]:
a + b

array([[36, 38, 37, 39, 41, 41],
       [42, 44, 43, 45, 47, 47],
       [48, 50, 49, 51, 53, 53],
       [54, 56, 55, 57, 59, 59],
       [60, 62, 61, 63, 65, 65],
       [66, 68, 67, 69, 71, 71]])

In [137]:
b = b.T

In [138]:
a+b

array([[36, 37, 38, 39, 40, 41],
       [43, 44, 45, 46, 47, 48],
       [47, 48, 49, 50, 51, 52],
       [54, 55, 56, 57, 58, 59],
       [61, 62, 63, 64, 65, 66],
       [66, 67, 68, 69, 70, 71]])