In [43]:
import numpy as np

In [53]:
a = np.fromfunction(lambda i,j,z :i*j*z ,(4,3,2),dtype=int)

In [54]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [56]:
a.reshape(4,2,1,3,1,1)

array([[[[[[0]],

          [[0]],

          [[0]]]],



        [[[[0]],

          [[0]],

          [[0]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[1]],

          [[0]],

          [[2]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[2]],

          [[0]],

          [[4]]]]],




       [[[[[0]],

          [[0]],

          [[0]]]],



        [[[[3]],

          [[0]],

          [[6]]]]]])

In [49]:
pd.DataFrame(a.reshape(1,24))

0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0   0   0   0   0   0   0   0   0   0   1  ...   0   2   0   4   0   0   0   

   21  22  23  
0   3   0   6  

[1 rows x 24 columns]

In [3]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [4]:
a.ndim

3

In [5]:
a.size

24

In [7]:
a.shape

(4, 3, 2)

In [8]:
a.dtype

dtype('int64')

In [9]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [10]:
import pandas as pd

In [50]:
a = np.fromfunction(lambda i,j :i*j ,(400,100),dtype=int)

In [15]:
a

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

ValueError: cannot reshape array of size 40000 into shape (4,2,1,3)

In [16]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

np.random.rand

In [18]:
np.random.rand(100,4)

array([[9.56599823e-01, 1.67087693e-01, 1.01552652e-01, 6.68582554e-01],
       [8.13890082e-01, 3.05889263e-01, 7.39344978e-01, 1.25329888e-01],
       [9.04629795e-01, 8.43149469e-02, 2.13460098e-01, 2.81671343e-02],
       [7.60170485e-01, 9.95964631e-02, 9.31427258e-01, 1.60325299e-01],
       [7.87231050e-01, 2.48252470e-01, 4.30819338e-01, 3.00677640e-01],
       [1.51746169e-01, 1.80694647e-01, 9.81689976e-01, 6.33997657e-01],
       [7.71125094e-01, 8.12132764e-01, 1.81949888e-01, 6.58471534e-01],
       [1.01823730e-01, 9.52223059e-02, 8.77899819e-01, 5.84749686e-01],
       [6.41764833e-01, 2.78532616e-01, 9.74327231e-01, 6.30439119e-01],
       [9.02733517e-01, 2.08305065e-01, 2.00685534e-01, 8.03274103e-01],
       [4.37335041e-01, 9.31215841e-01, 3.07858664e-01, 9.43520363e-01],
       [5.40210513e-01, 3.10049788e-01, 6.13104885e-02, 6.76079751e-01],
       [6.32212163e-01, 5.46224871e-01, 9.49016251e-01, 4.78595115e-01],
       [5.84121061e-01, 5.67012339e-01, 9.74227693e

In [20]:
np.random.rand(1000,10)

array([[0.63456646, 0.11943755, 0.24397999, ..., 0.93302069, 0.44020677,
        0.64644536],
       [0.89196456, 0.17059456, 0.81202879, ..., 0.0098961 , 0.80258008,
        0.66588728],
       [0.95017047, 0.54311673, 0.35347829, ..., 0.71764938, 0.60424659,
        0.04056901],
       ...,
       [0.79146673, 0.2214534 , 0.31050351, ..., 0.77651539, 0.48872857,
        0.72321689],
       [0.0551049 , 0.63913913, 0.57238229, ..., 0.25609515, 0.86164377,
        0.70559997],
       [0.94298513, 0.62470834, 0.85432312, ..., 0.28799602, 0.59189234,
        0.96746962]])

In [28]:
np.random.randint(4,50)

36

In [29]:
np.random.randn(4,5)

array([[ 0.00976255,  0.5853608 , -0.77986558, -0.59687756, -1.52666634],
       [-0.11842308,  1.04935515, -0.6887485 ,  1.29541721, -1.0222928 ],
       [ 0.50603531,  0.19475042, -0.79248776, -0.20549803,  0.28124628],
       [ 1.55531875,  0.36164573, -0.27261509, -0.58262756, -1.26760082]])

In [33]:
np.random.random_integers(1,100)

/tmp/ipykernel_3688/539065264.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  np.random.random_integers(1,100)


89

In [37]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.676753  0.025413 -1.646051  0.371256 -0.580734
1 -1.110874 -0.393155 -2.214082 -0.137830  0.656679
2  0.515543  1.301135  0.901024  1.214765  0.349357
3  1.109810  0.202939 -1.999143  0.847740 -0.543071

In [65]:
a.reshape(12,-1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [59]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [66]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [71]:
a.reshape(1,2,4,-234324)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [1, 0, 2]],

        [[0, 0, 0],
         [2, 0, 4],
         [0, 0, 0],
         [3, 0, 6]]]])

In [77]:
list(range(0,100,5))

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [80]:
list(range(0,10,2))

TypeError: 'float' object cannot be interpreted as an integer

In [81]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [82]:
np.arange(.4,10,0.2)

array([0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8,
       3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4,
       5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. ,
       8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

# 

In [84]:
np.arange(4,10.5,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [86]:
a1 = np.arange(4,10.5,2)

In [87]:
a1[1:5]

array([ 6.,  8., 10.])

In [88]:
arr = np.random.rand(4,5)

In [89]:
arr

array([[0.64045497, 0.86657775, 0.21638636, 0.79887145, 0.9930717 ],
       [0.06967824, 0.34433592, 0.78299478, 0.47853973, 0.09361645],
       [0.51514144, 0.38988765, 0.10897247, 0.70906272, 0.74214232],
       [0.19978039, 0.80883681, 0.76313816, 0.88173881, 0.35734974]])

In [90]:
arr >5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [92]:
arr[arr>.5]

array([0.64045497, 0.86657775, 0.79887145, 0.9930717 , 0.78299478,
       0.51514144, 0.70906272, 0.74214232, 0.80883681, 0.76313816,
       0.88173881])

In [95]:
arr[[1,2],[2]]

array([0.78299478, 0.10897247])

In [96]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [97]:
arr = np.random.rand(8,5)

In [98]:
arr

array([[0.98243725, 0.6163379 , 0.69377898, 0.03494503, 0.03235869],
       [0.52739997, 0.64006696, 0.77909513, 0.33675809, 0.46885036],
       [0.6656041 , 0.34329852, 0.65072007, 0.03766358, 0.84661052],
       [0.58766743, 0.35950669, 0.53204984, 0.20215048, 0.74416377],
       [0.99136762, 0.4935208 , 0.33519873, 0.20669772, 0.66764728],
       [0.74356862, 0.66572669, 0.02056303, 0.73698607, 0.68538239],
       [0.71953957, 0.38980191, 0.90534779, 0.91019842, 0.47317744],
       [0.13211365, 0.39663469, 0.61072498, 0.27936216, 0.04654893]])

In [105]:
arr[1:8],[0,1,2]

(array([[0.52739997, 0.64006696, 0.77909513, 0.33675809, 0.46885036],
        [0.6656041 , 0.34329852, 0.65072007, 0.03766358, 0.84661052],
        [0.58766743, 0.35950669, 0.53204984, 0.20215048, 0.74416377],
        [0.99136762, 0.4935208 , 0.33519873, 0.20669772, 0.66764728],
        [0.74356862, 0.66572669, 0.02056303, 0.73698607, 0.68538239],
        [0.71953957, 0.38980191, 0.90534779, 0.91019842, 0.47317744],
        [0.13211365, 0.39663469, 0.61072498, 0.27936216, 0.04654893]]),
 [0, 1, 2])

In [101]:
arr[1:8,0:3]

array([[0.52739997, 0.64006696, 0.77909513],
       [0.6656041 , 0.34329852, 0.65072007],
       [0.58766743, 0.35950669, 0.53204984],
       [0.99136762, 0.4935208 , 0.33519873],
       [0.74356862, 0.66572669, 0.02056303],
       [0.71953957, 0.38980191, 0.90534779],
       [0.13211365, 0.39663469, 0.61072498]])

In [106]:
a2 = arr[1:8],[0,1,2]

In [107]:
a2

(array([[0.52739997, 0.64006696, 0.77909513, 0.33675809, 0.46885036],
        [0.6656041 , 0.34329852, 0.65072007, 0.03766358, 0.84661052],
        [0.58766743, 0.35950669, 0.53204984, 0.20215048, 0.74416377],
        [0.99136762, 0.4935208 , 0.33519873, 0.20669772, 0.66764728],
        [0.74356862, 0.66572669, 0.02056303, 0.73698607, 0.68538239],
        [0.71953957, 0.38980191, 0.90534779, 0.91019842, 0.47317744],
        [0.13211365, 0.39663469, 0.61072498, 0.27936216, 0.04654893]]),
 [0, 1, 2])

In [110]:
a2[0][0] = 2435456

In [111]:
a2[0][0]

array([2435456., 2435456., 2435456., 2435456., 2435456.])

In [112]:
a2

(array([[2.43545600e+06, 2.43545600e+06, 2.43545600e+06, 2.43545600e+06,
         2.43545600e+06],
        [6.65604099e-01, 3.43298520e-01, 6.50720065e-01, 3.76635792e-02,
         8.46610516e-01],
        [5.87667427e-01, 3.59506692e-01, 5.32049835e-01, 2.02150477e-01,
         7.44163774e-01],
        [9.91367624e-01, 4.93520802e-01, 3.35198727e-01, 2.06697722e-01,
         6.67647280e-01],
        [7.43568625e-01, 6.65726691e-01, 2.05630283e-02, 7.36986068e-01,
         6.85382392e-01],
        [7.19539574e-01, 3.89801909e-01, 9.05347790e-01, 9.10198417e-01,
         4.73177441e-01],
        [1.32113649e-01, 3.96634692e-01, 6.10724981e-01, 2.79362164e-01,
         4.65489311e-02]]),
 [0, 1, 2])

In [115]:
a = np.array([[1,2],[3,4]])

In [116]:
b = np.array([[2,3],[4,5]])

In [117]:
a*b

array([[ 2,  6],
       [12, 20]])

In [118]:
a@b

array([[10, 13],
       [22, 29]])

In [119]:
k = a@b

In [120]:
k/0

/tmp/ipykernel_3688/387944184.py:1: RuntimeWarning: divide by zero encountered in divide
  k/0


array([[inf, inf],
       [inf, inf]])